name: Run Daily Script

# on:
#   schedule:
#     - cron: '0 0 * * *' # Run daily at midnight UTC
on:
  push:
    branches:
      - master

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests prettytable colored argparse beautifulsoup4

    - name: Run Script
      run: python main.py --vendor "totolink" --html "1.html"
    - name: Commit and Push Results
      run: |
        git config --global user.email "cnitlrt@github.com"
        git config --global user.name "cnitlrt"
        git add .
        git commit -m "Update results [skip ci]"
        git push
      env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}